export enum BancoEnum {
  BANCO_DO_BRASIL = 'BANCO_DO_BRASIL',
  SANTANDER = 'SANTANDER',
  CAIXA = 'CAIXA',
  BRADESCO = 'BRADESCO',
  ITAU = 'ITAU',
  NUBANK = 'NUBANK',
  INTER = 'INTER',
  C6 = 'C6',
  MERCADO_PAGO = 'MERCADO_PAGO',
  PAGBANK = 'PAGBANK',
  STONE = 'STONE',
  SICREDI = 'SICREDI',
  SICOOB = 'SICOOB',
  BANRISUL = 'BANRISUL',
  BTG_PACTUAL = 'BTG_PACTUAL',
  ORIGINAL = 'ORIGINAL',
  SAFRA = 'SAFRA',
  XP = 'XP',
  OUTRO = 'OUTRO',
}

export const BANCO_LABELS: Record<BancoEnum, string> = {
  [BancoEnum.BANCO_DO_BRASIL]: '001 - Banco do Brasil',
  [BancoEnum.SANTANDER]: '033 - Santander',
  [BancoEnum.CAIXA]: '104 - Caixa Econômica Federal',
  [BancoEnum.BRADESCO]: '237 - Bradesco',
  [BancoEnum.ITAU]: '341 - Itaú Unibanco',
  [BancoEnum.NUBANK]: '260 - Nu Pagamentos',
  [BancoEnum.INTER]: '077 - Banco Inter',
  [BancoEnum.C6]: '336 - C6 Bank',
  [BancoEnum.MERCADO_PAGO]: '323 - Mercado Pago',
  [BancoEnum.PAGBANK]: '290 - PagBank',
  [BancoEnum.STONE]: '197 - Stone',
  [BancoEnum.SICREDI]: '748 - Sicredi',
  [BancoEnum.SICOOB]: '756 - Sicoob',
  [BancoEnum.BANRISUL]: '041 - Banrisul',
  [BancoEnum.BTG_PACTUAL]: '208 - BTG Pactual',
  [BancoEnum.ORIGINAL]: '212 - Banco Original',
  [BancoEnum.SAFRA]: '422 - Safra',
  [BancoEnum.XP]: '348 - Banco XP',
  [BancoEnum.OUTRO]: '999 - Outro',
};
