export enum UfEnum {
  AC = 'AC',
  AL = 'AL',
  AP = 'AP',
  AM = 'AM',
  BA = 'BA',
  CE = 'CE',
  DF = 'DF',
  ES = 'ES',
  GO = 'GO',
  MA = 'MA',
  MT = 'MT',
  MS = 'MS',
  MG = 'MG',
  PA = 'PA',
  PB = 'PB',
  PR = 'PR',
  PE = 'PE',
  PI = 'PI',
  RJ = 'RJ',
  RN = 'RN',
  RS = 'RS',
  RO = 'RO',
  RR = 'RR',
  SC = 'SC',
  SP = 'SP',
  SE = 'SE',
  TO = 'TO',
}

export const UF_LABELS: Record<UfEnum, string> = {
  [UfEnum.AC]: 'AC - Acre',
  [UfEnum.AL]: 'AL - Alagoas',
  [UfEnum.AP]: 'AP - Amapá',
  [UfEnum.AM]: 'AM - Amazonas',
  [UfEnum.BA]: 'BA - Bahia',
  [UfEnum.CE]: 'CE - Ceará',
  [UfEnum.DF]: 'DF - Distrito Federal',
  [UfEnum.ES]: 'ES - Espírito Santo',
  [UfEnum.GO]: 'GO - Goiás',
  [UfEnum.MA]: 'MA - Maranhão',
  [UfEnum.MT]: 'MT - Mato Grosso',
  [UfEnum.MS]: 'MS - Mato Grosso do Sul',
  [UfEnum.MG]: 'MG - Minas Gerais',
  [UfEnum.PA]: 'PA - Pará',
  [UfEnum.PB]: 'PB - Paraíba',
  [UfEnum.PR]: 'PR - Paraná',
  [UfEnum.PE]: 'PE - Pernambuco',
  [UfEnum.PI]: 'PI - Piauí',
  [UfEnum.RJ]: 'RJ - Rio de Janeiro',
  [UfEnum.RN]: 'RN - Rio Grande do Norte',
  [UfEnum.RS]: 'RS - Rio Grande do Sul',
  [UfEnum.RO]: 'RO - Rondônia',
  [UfEnum.RR]: 'RR - Roraima',
  [UfEnum.SC]: 'SC - Santa Catarina',
  [UfEnum.SP]: 'SP - São Paulo',
  [UfEnum.SE]: 'SE - Sergipe',
  [UfEnum.TO]: 'TO - Tocantins',
};
