import {Component} from '@angular/core'; import {ActivatedRoute,Router} from '@angular/router';
import {FuncionarioDTO} from '../../../../dtos/funcionario/funcionario.dto'; import {FuncionarioCreateDTO} from '../../../../dtos/funcionario/funcionario.create.dto'; import {FuncionarioService} from '../../../../services/funcionario.service'; import {PessoaDTO} from '../../../../dtos/pessoa/pessoa.dto'; import {PessoaService} from '../../../../services/pessoa.service'; import {BaseFormCrud} from '../../../../shared/components-commons/core/base.form.crud'; import {ToolbarComponent} from '../../../../shared/components-commons/infra/toolbar-filter-component/toolbar.component'; import {PessoaSelectorComponent} from '../../../../shared/components-commons/pessoa-selector-component/pessoa.selector.component'; import {TextBoxComponent} from '../../../../shared/components-commons/infra/text-box-component/text.box.component'; import {DateBoxComponent} from '../../../../shared/components-commons/infra/date-box-component/date.box.component'; import {NumberBoxComponent} from '../../../../shared/components-commons/infra/number-box-component/number.box.component'; import {SwitchComponent} from '../../../../shared/components-commons/infra/switch-component/switch.component'; import {ValidationUtils} from '../../../../shared/utils/validation.utils';
@Component({standalone:true,imports:[ToolbarComponent,PessoaSelectorComponent,TextBoxComponent,DateBoxComponent,NumberBoxComponent,SwitchComponent],templateUrl:'./funcionario.form.component.html',styleUrl:'./funcionario.form.component.scss'})
export class FuncionarioFormComponent extends BaseFormCrud<FuncionarioDTO,FuncionarioCreateDTO>{
 protected service:FuncionarioService;protected routeBase='/app/cadastros/funcionario';pessoa?:PessoaDTO;
 constructor(s:FuncionarioService,r:Router,a:ActivatedRoute,private pessoas:PessoaService){super(r,a);this.service=s;this.model={pessoaId:0,cargo:'',dataAdmissao:'',ativo:true};}
 ngOnInit(){const value=this.route.snapshot.paramMap.get('id');if(value){this.id=Number(value);this.loading=true;this.service.getById(this.id).subscribe({next:r=>{const f=r.body;if(f){this.pessoa=f.pessoa;this.model={pessoaId:f.pessoa.id,cargo:f.cargo??'',dataAdmissao:f.dataAdmissao,dataDemissao:f.dataDemissao,salario:f.salario,ativo:f.ativo};}this.loading=false;},error:()=>this.loading=false});}else{const pessoaId=Number(this.route.snapshot.queryParamMap.get('pessoaId'));if(pessoaId)this.pessoas.getById(pessoaId).subscribe(r=>this.selecionar(r.body??undefined));}}
 selecionar(p?:PessoaDTO){this.pessoa=p;this.model.pessoaId=p?.id??0;}
 novaPessoa(){this.router.navigate(['/app/cadastros/pessoa/create'],{queryParams:{returnUrl:this.router.url.split('?')[0]}});}
 override validateSave(){if(!this.model.pessoaId){this.alertService.warning('Selecione a pessoa.');return false;}if(!ValidationUtils.required(this.model.dataAdmissao)){this.alertService.warning('Informe a data de admissão.');return false;}return true;}
}
