import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { finalize } from 'rxjs';
import { DocumentoFiscalCreateDTO, DocumentoFiscalDTO, DocumentoFiscalVinculoCreateDTO } from '../../dtos/documento-fiscal/documento.fiscal';
import { LancamentoFinanceiroDTO } from '../../dtos/lancamento/lancamento.financeiro';
import { PessoaDTO } from '../../dtos/pessoa/pessoa.dto';
import { SituacaoDocumentoFiscalEnum, SITUACAO_DOCUMENTO_FISCAL_LABELS, TipoDocumentoFiscalEnum, TIPO_DOCUMENTO_FISCAL_LABELS } from '../../enums/documento.fiscal.enum';
import { DocumentoFiscalService } from '../../services/documento-fiscal.service';
import { LancamentoFinanceiroService } from '../../services/lancamento-financeiro.service';
import { AlertService } from '../../shared/components-commons/infra/alert-component/alert.service';
import { DateBoxComponent } from '../../shared/components-commons/infra/date-box-component/date.box.component';
import { NumberBoxComponent } from '../../shared/components-commons/infra/number-box-component/number.box.component';
import { SelectEnumComponent } from '../../shared/components-commons/infra/select-enum-component/select.enum.component';
import { TextBoxComponent } from '../../shared/components-commons/infra/text-box-component/text.box.component';
import { ToolbarComponent } from '../../shared/components-commons/infra/toolbar-filter-component/toolbar.component';
import { PessoaSelectorComponent } from '../../shared/components-commons/pessoa-selector-component/pessoa.selector.component';
@Component({standalone:true,imports:[CommonModule,FormsModule,ToolbarComponent,TextBoxComponent,SelectEnumComponent,DateBoxComponent,NumberBoxComponent,PessoaSelectorComponent],template:`
<toolbar-filter tituloPagina="Documento fiscal" [listMode]="false" [loading]="loading" (salvar)="salvar()" (limpar)="limpar()" />
<section class="page"><div class="heading"><i class="bi bi-receipt"></i><div><h2>Dados do documento fiscal</h2><p>Informe a nota e distribua seu valor entre os lançamentos de receita.</p></div></div>
<div class="xml-import">
  <div class="xml-copy"><i class="bi bi-filetype-xml"></i><div><strong>Preencher pelo XML</strong><span>O arquivo é usado somente para leitura e descartado em seguida.</span></div></div>
  <input #xmlInput type="file" accept=".xml,application/xml,text/xml" (change)="importarXml($event)" hidden>
  <button type="button" (click)="xmlInput.click()" [disabled]="loading||importandoXml"><i class="bi" [class.bi-upload]="!importandoXml" [class.bi-arrow-repeat]="importandoXml" [class.spin]="importandoXml"></i> {{importandoXml?'Lendo XML...':'Selecionar XML'}}</button>
</div>
@if(clienteXmlNaoEncontrado){<div class="xml-warning"><i class="bi bi-exclamation-triangle"></i><span>Cliente do XML não encontrado no cadastro: <strong>{{clienteXmlNaoEncontrado}}</strong>. Selecione ou cadastre a pessoa antes de salvar, se necessário.</span></div>}
<div class="fields">
  <div class="field-row"><date-box-component label="Data de emissão" width="210px" [clearButton]="true" [(dataField)]="model.dataEmissao" [disabled]="loading"/><select-enum label="Tipo" width="210px" [enumObject]="tipos" [optionLabels]="tipoLabels" [(dataField)]="model.tipo" [disabled]="loading"/></div>
  <div class="field-row"><text-box-component label="Número" width="270px" [(dataField)]="model.numero" [disabled]="loading"/><text-box-component label="Série" width="150px" [(dataField)]="model.serie" [disabled]="loading"/></div>
  <div class="field-row"><pessoa-selector-component label="Cliente" width="435px" [pessoa]="cliente" (pessoaChange)="selecionarCliente($event)" [disabled]="loading"/></div>
  <div class="field-row"><text-box-component label="Chave de acesso" width="435px" [(dataField)]="model.chaveAcesso" [disabled]="loading"/></div>
  <div class="field-row"><number-box-component label="Valor total" width="210px" [(dataField)]="model.valorTotal" [disabled]="loading"/><select-enum label="Situação" width="210px" [enumObject]="situacoes" [optionLabels]="situacaoLabels" [(dataField)]="model.situacao" [disabled]="loading"/></div>
  <div class="field-row"><label class="observation"><span>Observação</span><textarea [(ngModel)]="model.observacao" [disabled]="loading"></textarea></label></div>
</div>
<section class="links"><div class="links-heading"><div><h3>Vínculos financeiros</h3><p>O total vinculado não pode ultrapassar o documento nem o lançamento.</p></div><div class="totals"><span>Vinculado <strong>{{totalVinculado|currency:'BRL'}}</strong></span><span>Saldo <strong>{{saldoVincular|currency:'BRL'}}</strong></span></div></div>
<div class="add-link"><label><span>Lançamento de receita</span><select [(ngModel)]="lancamentoSelecionado"><option [ngValue]="undefined">Selecione</option>@for(item of lancamentosDisponiveis;track item.id){<option [ngValue]="item.id">{{item.descricao}} — {{item.valor|currency:'BRL'}}</option>}</select></label><number-box-component label="Valor vinculado" width="200px" [(dataField)]="valorVinculo"/><button (click)="adicionarVinculo()" [disabled]="loading"><i class="bi bi-plus"></i> Adicionar</button></div>
<div class="table-responsive"><table><thead><tr><th>Lançamento</th><th>Competência</th><th>Valor do lançamento</th><th>Valor vinculado</th><th></th></tr></thead><tbody>@if(!model.vinculos.length){<tr><td colspan="5" class="empty">Nenhum lançamento vinculado.</td></tr>}@else{@for(vinculo of model.vinculos;track vinculo.lancamentoId){<tr><td>{{descricaoLancamento(vinculo.lancamentoId)}}</td><td>{{competenciaLancamento(vinculo.lancamentoId)|date:'MM/yyyy':'UTC'}}</td><td>{{valorLancamento(vinculo.lancamentoId)|currency:'BRL'}}</td><td><input type="number" min="0.01" step="0.01" [(ngModel)]="vinculo.valorVinculado"/></td><td><button class="remove" (click)="removerVinculo(vinculo.lancamentoId)"><i class="bi bi-trash"></i></button></td></tr>}}</tbody></table></div></section></section>`,styles:[`
.page{margin-top:1rem;padding:1.5rem;background:#fff;border-radius:12px}.heading{display:flex;gap:.8rem;align-items:center}.heading>i{display:grid;place-items:center;width:44px;height:44px;border-radius:10px;background:#eef1ff;color:#5570f1;font-size:1.2rem}.heading h2,.links h3{margin:0}.heading p,.links p{margin:.2rem 0;color:#687080}.xml-import{display:flex;align-items:center;justify-content:space-between;gap:1rem;width:435px;max-width:100%;margin-top:1.5rem;padding:.8rem;border:1px dashed #aeb9ec;border-radius:9px;background:#f8f9ff}.xml-copy{display:flex;align-items:center;gap:.7rem}.xml-copy>i{font-size:1.5rem;color:#5570f1}.xml-copy div{display:flex;flex-direction:column}.xml-copy span{font-size:.76rem;color:#687080}.xml-import button{flex:none;height:36px;padding:0 .75rem;border:1px solid #5570f1;border-radius:6px;background:#fff;color:#4055ba}.xml-warning{display:flex;gap:.6rem;width:435px;max-width:100%;margin-top:.8rem;padding:.7rem;border-radius:7px;background:#fff4d6;color:#745700;font-size:.85rem}.spin{display:inline-block;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.fields{display:flex;flex-direction:column;gap:1rem;margin-top:1.5rem}.field-row{display:flex;gap:15px;align-items:end;flex-wrap:wrap;width:435px;max-width:100%}.observation{display:flex;flex-direction:column;width:435px;max-width:100%;gap:.4rem}.observation span,.add-link label>span{font-weight:500}.observation textarea{width:100%;min-height:90px;padding:.65rem;border:1px solid #ced4da;border-radius:6px}.links{margin-top:1.5rem;padding-top:1.5rem;border-top:1px solid #e6e9ef}.links-heading{display:flex;justify-content:space-between;gap:1rem}.totals{display:flex;gap:1rem}.totals span{display:flex;flex-direction:column;color:#687080}.totals strong{color:#263d50}.add-link{display:flex;gap:1rem;align-items:end;flex-wrap:wrap;margin:1rem 0}.add-link label{display:flex;flex-direction:column;gap:.4rem;width:435px;max-width:100%}.add-link select,.add-link button{height:38px;border:1px solid #ced4da;border-radius:6px;background:#fff;padding:0 .7rem}.add-link button{border-color:#5570f1;color:#4055ba}.table-responsive{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.7rem;border-bottom:1px solid #eceef3;text-align:left}th{font-size:.8rem;color:#687080}td input{width:150px;padding:.4rem;border:1px solid #ced4da;border-radius:5px}.remove{width:34px;height:34px;border:1px solid #e3a5aa;border-radius:6px;background:#fff;color:#b02a37}.empty{text-align:center;color:#687080;padding:2rem}@media(max-width:700px){.links-heading{flex-direction:column}.totals{justify-content:space-between}.field-row{width:100%}.xml-import{align-items:stretch;flex-direction:column}.xml-import button{align-self:flex-start}}
`]})
export class DocumentoFiscalFormComponent implements OnInit{
 id?:number;loading=false;importandoXml=false;clienteXmlNaoEncontrado='';cliente?:PessoaDTO;lancamentos:LancamentoFinanceiroDTO[]=[];lancamentoSelecionado?:number;valorVinculo=0;tipos=TipoDocumentoFiscalEnum;tipoLabels=TIPO_DOCUMENTO_FISCAL_LABELS;situacoes=SituacaoDocumentoFiscalEnum;situacaoLabels=SITUACAO_DOCUMENTO_FISCAL_LABELS;model:DocumentoFiscalCreateDTO=this.novoModelo();
 constructor(private service:DocumentoFiscalService,private lancamentoService:LancamentoFinanceiroService,private route:ActivatedRoute,private router:Router,private alerts:AlertService){}
 ngOnInit(){this.id=Number(this.route.snapshot.paramMap.get('id'))||undefined;this.carregarLancamentos();if(this.id)this.carregar();}
 get lancamentosDisponiveis(){return this.lancamentos.filter(l=>l.tipo==='RECEBER'&&l.situacao!=='CANCELADO'&&!this.model.vinculos.some(v=>v.lancamentoId===l.id));}
 get totalVinculado(){return this.model.vinculos.reduce((t,v)=>t+(Number(v.valorVinculado)||0),0);}get saldoVincular(){return (Number(this.model.valorTotal)||0)-this.totalVinculado;}
 carregarLancamentos(){this.lancamentoService.getAll().subscribe(r=>this.lancamentos=r.body??[]);}
 carregar(){this.loading=true;this.service.getById(this.id!).pipe(finalize(()=>this.loading=false)).subscribe({next:r=>{const d=r.body!;this.model={tipo:d.tipo,numero:d.numero,serie:d.serie??'',chaveAcesso:d.chaveAcesso??'',dataEmissao:d.dataEmissao,valorTotal:d.valorTotal,situacao:d.situacao,clienteId:d.clienteId,observacao:d.observacao??'',vinculos:d.vinculos.map(v=>({lancamentoId:v.lancamentoId,valorVinculado:v.valorVinculado}))};if(d.clienteId)this.cliente={id:d.clienteId,nomeRazaoSocial:d.clienteNome} as PessoaDTO;},error:e=>this.alerts.error(e?.error?.messages?.join('<br>')||'Não foi possível carregar o documento.')});}
 selecionarCliente(p?:PessoaDTO){this.cliente=p;this.model.clienteId=p?.id;}
 importarXml(event:Event){const input=event.target as HTMLInputElement;const arquivo=input.files?.[0];if(!arquivo)return;if(!arquivo.name.toLowerCase().endsWith('.xml')){this.alerts.warning('Selecione um arquivo XML.');input.value='';return;}if(arquivo.size>2*1024*1024){this.alerts.warning('O XML deve ter no máximo 2 MB.');input.value='';return;}this.importandoXml=true;this.clienteXmlNaoEncontrado='';this.service.importarXml(arquivo).pipe(finalize(()=>{this.importandoXml=false;input.value='';})).subscribe({next:d=>{this.model.tipo=d.tipo;this.model.numero=d.numero;this.model.serie=d.serie??'';this.model.chaveAcesso=d.chaveAcesso??'';this.model.dataEmissao=d.dataEmissao;this.model.valorTotal=d.valorTotal;this.model.situacao=SituacaoDocumentoFiscalEnum.EMITIDO;if(d.clienteEncontrado&&d.clienteId){this.cliente={id:d.clienteId,nomeRazaoSocial:d.clienteNome} as PessoaDTO;this.model.clienteId=d.clienteId;}else{this.cliente=undefined;this.model.clienteId=undefined;this.clienteXmlNaoEncontrado=[d.clienteNome,d.clienteDocumento].filter(Boolean).join(' — ');}this.alerts.success('Dados do XML preenchidos com sucesso.');},error:e=>this.alerts.error(e?.error?.messages?.join('<br>')||'Não foi possível importar o XML.')});}
 adicionarVinculo(){if(!this.lancamentoSelecionado||!this.valorVinculo){this.alerts.warning('Selecione o lançamento e informe o valor do vínculo.');return;}this.model.vinculos.push({lancamentoId:this.lancamentoSelecionado,valorVinculado:this.valorVinculo});this.lancamentoSelecionado=undefined;this.valorVinculo=0;}
 removerVinculo(id:number){this.model.vinculos=this.model.vinculos.filter(v=>v.lancamentoId!==id);}
 descricaoLancamento(id:number){return this.lancamentos.find(l=>l.id===id)?.descricao??`Lançamento #${id}`;}competenciaLancamento(id:number){return this.lancamentos.find(l=>l.id===id)?.dataCompetencia;}valorLancamento(id:number){return this.lancamentos.find(l=>l.id===id)?.valor??0;}
 salvar(){if(this.loading)return;if(!this.model.tipo||!this.model.numero?.trim()||!this.model.dataEmissao||!this.model.valorTotal||!this.model.situacao){this.alerts.warning('Informe tipo, número, emissão, valor total e situação.');return;}if(this.saldoVincular<0){this.alerts.warning('O valor vinculado supera o valor do documento.');return;}this.loading=true;const req=this.id?this.service.update(this.id,this.model):this.service.create(this.model);req.pipe(finalize(()=>this.loading=false)).subscribe({next:()=>{this.alerts.success(this.id?'Documento atualizado com sucesso.':'Documento cadastrado com sucesso.');this.router.navigate(['/app/fiscal/documentos']);},error:e=>this.alerts.error(e?.error?.messages?.join('<br>')||'Não foi possível salvar o documento.')});}
 limpar(){this.model=this.novoModelo();this.cliente=undefined;this.clienteXmlNaoEncontrado='';}
 private novoModelo():DocumentoFiscalCreateDTO{return{tipo:TipoDocumentoFiscalEnum.NFSE,numero:'',serie:'',chaveAcesso:'',dataEmissao:new Date().toISOString().slice(0,10),valorTotal:0,situacao:SituacaoDocumentoFiscalEnum.EMITIDO,observacao:'',vinculos:[]};}
}
